name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]


env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and push image Aliyun
      run: |
        # 通过标准输入使用密码（更安全）
        echo "$ALIYUN_REGISTRY_PASSWORD" | docker login -u "$ALIYUN_REGISTRY_USER" --password-stdin "$ALIYUN_REGISTRY"
        while read line; do
          docker pull "$line" || { echo "拉取镜像出错: $line"; exit 1; } # 如果拉取失败则退出
          image_name_tag=$(echo "$line" | awk -F'/' '{print $NF}')
          new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$image_name_tag"
          docker tag "$line" "$new_image" || { echo "标记镜像出错: $line"; exit 1; }
          echo "正在推送 $new_image"
          docker push "$new_image" || { echo "推送镜像出错: $new_image"; exit 1; }
        done < images.txt
